# Generated by Django 6.0.6 on 2026-07-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('class_name', models.CharField(max_length=30)),
                ('study_hours_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('parental_education', models.CharField(choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctorate', 'Doctorate')], max_length=20)),
                ('internet_access', models.BooleanField(default=True)),
                ('extracurricular_activities', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_final_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_performance_level', models.CharField(default='Unknown', max_length=20)),
                ('predicted_pass', models.BooleanField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('science_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('english_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_year_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('performance_level', models.CharField(default='Unknown', max_length=20)),
                ('passed', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
        ),
    ]
