# Generated by Django 6.0.6 on 2026-07-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('study_hours_per_week', models.DecimalField(decimal_places=1, max_digits=4)),
                ('previous_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('current_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predicted_pass', models.BooleanField()),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('homework_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quiz_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('midterm_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_exam_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
        ),
    ]
